### PR TITLE
Fix tui artifacts by removing carriage returns

### LINKED ISSUE #144: Carriage returns cause graphical artifacts in TUI
Hi, really useful project!  I noticed the presence of carriage returns in the vault files causes some glitching in the TUI:

Image

So will submit a PR!

### PR DESCRIPTION
**Pull request by mstorick**
Closes #144

### CODE REVIEW

File: vault-tasks-core/src/tracker.rs [hunk 1]
```diff
@@ -147,11 +147,13 @@ impl Tracker {
         }
         let new_lines = self
             .fmt(config.core.use_american_format)
+            .replace("\r", "")
```
Comment (louis-thevenet) [inline vault-tasks-core/src/tracker.rs]:
```suggestion
            .replace('\r', "")
```

File: vault-tasks-core/src/tracker.rs [hunk 2]
```diff
@@ -147,11 +147,13 @@ impl Tracker {
...
             .split('\n')
             .map(str::to_owned)
             .collect::<Vec<String>>();
         let content = read_to_string(path)?;
         let mut lines = content
+            .replace("\r", "")
```
Comment (louis-thevenet) [inline vault-tasks-core/src/tracker.rs]:
```suggestion
            .replace('\r', "")
```

File: vault-tasks-core/src/vault_data.rs [hunk 3]
```diff
@@ -53,20 +53,24 @@ impl Display for VaultData {
...
+                    for line in task.to_string().replace("\r", "").split('\n') {
                         write_indent(depth, f)?;
                         writeln!(f, "{line}")?;
                     }
 
                     for subtask in &task.subtasks {
-                        for line in VaultData::Task(subtask.clone()).to_string().split('\n') {
+                        for line in VaultData::Task(subtask.clone())
+                            .to_string()
+                            .replace("\r", "")
```
Comment (louis-thevenet) [inline vault-tasks-core/src/vault_data.rs]:
```suggestion
                            .replace('\r', "")
```

**Review by louis-thevenet — CHANGES_REQUESTED** [review]
Hi! Thank you for the PR and your interest in the project. =)
That’s an issue I’ve never encountered on Linux.

Just a small detail (Clippy is screaming at me) to address, and we’re good to merge!
